// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { env_config } from "./src/config/env-config.js";

export default defineConfig({
  schema: "src/prisma/",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: env_config.database_url,
  },
});
